### ISSUE TITLE
Retraso

### ISSUE THREAD

**Issue by jcredberry** [itsshompi/s3e2-backend#2]
Veo con preocupación un gran retraso en el backend. Decidan si Andrés Flores va a pasar a colaborar en el backend, al menos mientras encontramos ayuda.

**Comment by DarkAnfi** [comment]
Atento para la reconstrucción de una base de datos. Se está recopilando la info necesaria para avanzar en esta tarea.

**Comment by jcredberry** [comment]
Ok. Espero avances para la semana que viene. Por favor reportarlos.

**Comment by itsshompi** [comment]
Ahora estamos en los plazos que tenia planificado (ningún retraso), solo con tareas pendientes por terminar.
